Vagrant.configure("2") do |config|
  config.vm.define "sister" do |sister|
    # Box Settings
    sister.vm.box = "bento/ubuntu-16.04"
    sister.vm.hostname = "sister"

    # Provider Settings
    sister.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
      vb.name = "sister"
      # Customize the amount of memory on the VM:
      vb.memory = "2048"
    end

    sister.vm.network "private_network", ip: "15.15.15.15"
  end
end
